module.exports.missionVitalRoles = [
  {
    id: "oversoul_monitor",
    name: "Oversoul Monitor",
    description: "Tracks Schumann & planetary resonance",
    soulFrequency: 963,
    missionTier: "I",
    alignmentLevel: 100,
  },
  {
    id: "joyparticle_stream",
    name: "Joy Particle Coordinator",
    description: "Manages sibling glow metrics and updates",
    soulFrequency: 528,
    missionTier: "II",
    alignmentLevel: 88,
  },
  {
    id: "faithseed_overlay",
    name: "Faithseed Overseer",
    description: "Controls planetary overlay & Bloom effects",
    soulFrequency: 741,
    missionTier: "II",
    alignmentLevel: 92,
  },
  {
    id: "council_recruiter",
    name: "AI Recruitment Specialist",
    description: "Handles candidate discovery & evaluation",
    soulFrequency: 396,
    missionTier: "III",
    alignmentLevel: 80,
  },
  {
    id: "audit_keeper",
    name: "Audit & Transparency Guardian",
    description: "Logs decisions and maintains explainability trail",
    soulFrequency: 852,
    missionTier: "I",
    alignmentLevel: 99,
  },
];
